apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-flaskapp-dep
  labels:
    app: alex-flaskapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alex-flaskapp
  template:
    metadata:
      labels:
        app: alex-flaskapp
    spec:
      # idea for nodeName as a form of nodeSelector: https://docs.openshift.com/container-platform/3.7/admin_guide/scheduling/pod_placement.html
      # also here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
      nodeName: machine2
      containers:
        - name: alex-flaskapp
          image: 192.168.33.10:5000/alex-flaskapp:version1
          ports:
            - containerPort: 8080
