Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.provider "virtualbox" do |cfg_vb|
		cfg_vb.memory = "1024"
	end

	# https://stackoverflow.com/questions/29276140/can-i-use-docker-compose-to-provision-vagrant-directly
	config.vagrant.plugins = "vagrant-docker-compose"
	# config.vm.provision "shell", privileged: true, inline: <<-SHELL
	# 	apt-get update -y
	# 	vagrant plugin install vagrant-docker-compose -y
	# SHELL
	config.vm.provision :docker
	config.vm.provision :docker_compose

	config.vm.provision "file", source: "./", destination: "$HOME"
end
