apiVersion: v1
kind: Pod
metadata:
  name: alex-flaskapp
  labels:
     app: alex-flaskapp
spec:
  # idea for nodeName as a form of nodeSelector: https://docs.openshift.com/container-platform/3.7/admin_guide/scheduling/pod_placement.html
  # also here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
  nodeName: machine2
  containers:
  - image: 192.168.33.10:5000/alex-flaskapp:version1
    name: alex-flaskapp
    ports:
    - containerPort: 8080
      protocol: TCP
